Repository smarr/SOMns, pull requests merged in 2018-02, with the labels that each got.

#217 Add support for Unicode codepoints
  core-lib/Kernel.ns
  core-lib/TestSuite/StringTests.ns
  docs/naming.md
  mkdocs.yml
  som
  src/som/compiler/Lexer.java
  src/som/interpreter/nodes/InstantiationNode.java
  src/som/interpreter/nodes/IsValueCheckNode.java
  src/som/primitives/ActivitySpawn.java
  src/som/primitives/StringPrims.java
  src/som/primitives/actors/CreateActorPrim.java
  src/som/primitives/processes/ChannelPrimitives.java
  src/som/vm/constants/KernelObj.java
  tests/dym/expected-results.tar.bz2
  tests/superinstructions/expected-results.tar.bz2
Labels: enhancement, language-design

#220 Improve File module
  .gitlab-ci.yml
  core-lib/Files.ns
  core-lib/Mirrors.ns
  core-lib/TestSuite/FileTests.ns
  som
  src/som/primitives/FilePrims.java
  src/som/primitives/MirrorPrims.java
  src/som/primitives/PathPrims.java
  src/som/vmobjects/SFileDescriptor.java
  tests/dym/expected-results.tar.bz2
  tests/dym/test.sh
  tests/superinstructions/expected-results.tar.bz2
Labels: enhancement

#215 Support Arbitrary Number of Block Arguments
  README.md
  core-lib/Kernel.ns
  core-lib/TestSuite/LanguageTests.ns
  src/som/interpreter/SArguments.java
  src/som/interpreter/nodes/literals/ArrayLiteralNode.java
  src/som/interpreter/nodes/literals/BlockNode.java
  src/som/primitives/BlockPrims.java
  src/som/vm/ObjectSystem.java
  src/som/vm/constants/Classes.java
  src/som/vmobjects/SBlock.java
  tests/dym/expected-results.tar.bz2
  tests/superinstructions/expected-results.tar.bz2
Labels: bug, enhancement, language-design

#224 Colorizing standard output
  core-lib/System.ns
  som
  src/som/Output.java
  src/som/UncaughtExceptions.java
  src/som/VM.java
  src/som/compiler/NumeralParser.java
  src/som/compiler/Parser.java
  src/som/interpreter/actors/Actor.java
  src/som/interpreter/nodes/dispatch/AbstractGenericDispatchNode.java
  src/som/interpreter/nodes/dispatch/CachedDnuNode.java
  src/som/primitives/ObjectPrims.java
  src/som/primitives/SystemPrims.java
  src/som/vm/ObjectSystem.java
  src/som/vm/VmOptions.java
  src/som/vm/VmSettings.java
  src/tools/concurrency/ActorExecutionTrace.java
  src/tools/concurrency/TraceParser.java
  src/tools/concurrency/TracingActors.java
  src/tools/debugger/WebSocketHandler.java
  tests/dym/expected-results.tar.bz2
  tools/kompos/tests/som-integration.ts
Labels: enhancement

#228 Simplify som launcher
  som
Labels: enhancement
