Repository smarr/SOMns, pull requests merged in 2018-03, with the labels that each got.

#229 Throw a proper SOMns Exception when a module isn't found
  core-lib/Files.ns
  src/som/Output.java
  src/som/primitives/SystemPrims.java
  src/som/vm/NotAFileException.java
  src/som/vm/ObjectSystem.java
  tests/dym/expected-results.tar.bz2
Labels: bug, enhancement

#204 Adapted Streams Library from Newspeak
  .gitignore
  build.xml
  core-lib/Files.ns
  core-lib/Platform.ns
  core-lib/Streams.ns
  core-lib/TestSuite/StreamTests.ns
  core-lib/TestSuite/TestRunner.ns
  src/som/primitives/SizeAndLengthPrim.java
  src/som/primitives/arrays/PutAllNode.java
  tests/dym/expected-results.tar.bz2
  tests/dym/test.sh
  tests/streams/Binary.blob
  tests/streams/Text.t
  tests/superinstructions/expected-results.tar.bz2
  tests/superinstructions/test.sh
Labels: enhancement

#232 Simplify setup and use of Graal
  .gitlab-ci.yml
  .travis.yml
  README.md
  build.xml
  codespeed.conf
  docs/basic-setup.md
  docs/dev-setup.md
  libs/java8/Unsafe.java
  som
  src/som/compiler/MethodBuilder.java
  src/som/compiler/MixinDefinition.java
  src/som/interpreter/actors/SPromise.java
  src/tools/dym/profiles/OperationProfile.java
Labels: enhancement, help wanted, question

#233 Handle method/mixin scope uniformly
  src/som/compiler/MethodBuilder.java
  src/som/compiler/MixinBuilder.java
  src/som/compiler/MixinDefinition.java
  src/som/compiler/Parser.java
  src/som/compiler/ScopeBuilder.java
  src/som/compiler/Variable.java
  src/som/interpreter/LexicalScope.java
  src/som/interpreter/Method.java
  src/som/interpreter/nodes/ExpressionNode.java
  src/som/vm/ObjectSystem.java
  src/som/vm/Primitives.java
Labels: enhancement

#242 Support JDK 10 and added testing
  .travis.yml
  build.xml
  docs/basic-setup.md
  docs/dev-setup.md
  src/som/primitives/ActivitySpawn.java
  src/som/primitives/MethodPrims.java
  src/som/primitives/arrays/ToArgumentsArrayFactory.java
Labels: bug

#244 Reduce race-related stack overflows, and handled invalid layouts in ClassSlotAccessNode
  src/som/compiler/MixinDefinition.java
  src/som/interpreter/nodes/dispatch/ClassSlotAccessNode.java
  src/som/interpreter/objectstorage/StorageLocation.java
  src/som/vmobjects/SClass.java
  src/som/vmobjects/SObject.java
  tests/java/som/tests/BasicInterpreterTests.java
Labels: bug

#243 Adopt Economic collections of GraalVM to ensure insertion order
  src/som/compiler/MethodBuilder.java
  src/som/compiler/MixinBuilder.java
  src/som/compiler/MixinDefinition.java
  src/som/interop/InteropDispatch.java
  src/som/interpreter/LexicalScope.java
  src/som/interpreter/actors/TransferObject.java
  src/som/interpreter/objectstorage/ClassFactory.java
  src/som/interpreter/objectstorage/ObjectLayout.java
  src/som/primitives/MirrorPrims.java
  src/som/vm/ObjectSystem.java
  src/som/vm/Primitives.java
  src/som/vmobjects/SClass.java
  src/som/vmobjects/SObject.java
  src/tools/debugger/message/VariablesResponse.java
  src/tools/dym/DynamicMetrics.java
  src/tools/dym/MetricsCsvWriter.java
Labels: bug

#238 Fix outer traversal to use lexical chain
  core-lib/TestSuite/LanguageTests.ns
  src/som/compiler/MethodBuilder.java
  src/som/interpreter/LexicalScope.java
  src/som/interpreter/SNodeFactory.java
  src/som/interpreter/nodes/OuterObjectRead.java
  src/som/interpreter/nodes/ResolvingImplicitReceiverSend.java
Labels: bug
