Repository smarr/SOMns, pull requests merged in 2019-08, with the labels that each got.

#306 Added citation details to README, and few updates
  README.md
Labels: enhancement

#292 Fix overflow bug in DividePrim
  core-lib/TestSuite/IntegerTests.ns
  src/som/primitives/arithmetic/DividePrim.java
Labels: bug

#309 Put Long#parseLong() behind boundary
  src/som/primitives/IntegerPrims.java
Labels: maintenance

#310 Fix termination in Launcher and of Fork/Join Pools
  src/som/Launcher.java
  src/som/VM.java
Labels: bug

#308 Multi-paradigm replay: CSP
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  build.xml
  codespeed.conf
  core-lib/Benchmarks/SavinaCSP.ns
  src/som/interpreter/actors/Actor.java
  src/som/interpreter/actors/SPromise.java
  src/som/interpreter/processes/SChannel.java
  src/som/primitives/ActivitySpawn.java
  src/som/primitives/SystemPrims.java
  src/som/primitives/TimerPrim.java
  src/som/primitives/processes/ChannelPrimitives.java
  src/som/vm/Activity.java
  src/tools/concurrency/TraceBuffer.java
  src/tools/concurrency/TraceParser.java
  src/tools/concurrency/TracingActivityThread.java
  src/tools/concurrency/TracingActors.java
  src/tools/concurrency/TracingChannel.java
  src/tools/replay/PassiveEntityWithEvents.java
  src/tools/replay/ReplayData.java
  src/tools/replay/ReplayRecord.java
  src/tools/replay/StringWrapper.java
  src/tools/replay/TraceParser.java
  src/tools/replay/actors/ActorExecutionTrace.java
  src/tools/replay/nodes/RecordEventNodes.java
  src/tools/replay/nodes/TraceActorContextNode.java
  src/tools/replay/nodes/TraceActorCreationNode.java
  src/tools/replay/nodes/TraceContextNode.java
  src/tools/replay/nodes/TraceMessageNode.java
  src/tools/snapshot/SnapshotBuffer.java
Labels: research

#313 Update Kompos' TypeScript dependencies and other details
  build.xml
  som
  src/som/VM.java
  tools/kompos/package.json
Labels: maintenance

#312 Restore performance of replay
  src/som/VM.java
  src/som/interpreter/actors/EventualMessage.java
  src/som/primitives/ActivitySpawn.java
  src/som/primitives/SystemPrims.java
  src/som/primitives/TimerPrim.java
  src/som/primitives/processes/ChannelPrimitives.java
  src/som/vm/Activity.java
  src/tools/concurrency/TracingActivityThread.java
  src/tools/concurrency/TracingActors.java
  src/tools/replay/ReplayData.java
  src/tools/replay/TraceParser.java
  src/tools/replay/TraceRecord.java
  src/tools/replay/actors/ActorExecutionTrace.java
  src/tools/replay/nodes/RecordEventNodes.java
  src/tools/replay/nodes/TraceActorCreationNode.java
  src/tools/replay/nodes/TraceContextNode.java
  src/tools/replay/nodes/TraceMessageNode.java
  tests/java/tools/replay/TraceParserTests.java
  tests/replay/fj-throughput/trace.dat
  tests/replay/fj-throughput/trace.sym
  tests/replay/fj-throughput/trace.trace
  tests/replay/val-messages-2/trace.dat
  tests/replay/val-messages-2/trace.sym
  tests/replay/val-messages-2/trace.trace
  tests/replay/val-messages/trace.dat
  tests/replay/val-messages/trace.sym
  tests/replay/val-messages/trace.trace
Labels: bug, enhancement

#319 Fix issue with clobber not working without JVMCI (resolves #316)
  build.xml
Labels: bug
