Repository smarr/SOMns, pull requests merged in 2022-10, with the labels that each got.

#388 Update Eclipse to Java 17 and various other cleanups
  .classpath
  .github/workflows/ci.yml
  .gitlab-ci.yml
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  build.xml
  core-lib/TestSuite/extension/.classpath
  core-lib/TestSuite/extension/.settings/org.eclipse.jdt.core.prefs
  core-lib/TestSuite/extension/.settings/org.eclipse.jdt.ui.prefs
  libs/java8/Unsafe.java
  src/som/interpreter/actors/SPromise.java
  src/som/interpreter/nodes/specialized/IntDownToDoInlinedLiteralsNode.java
  src/som/interpreter/nodes/specialized/IntToDoInlinedLiteralsNode.java
  src/som/interpreter/objectstorage/SafepointPhaser.java
  src/som/primitives/processes/ChannelPrimitives.java
  src/som/primitives/threading/TaskThreads.java
  src/som/vm/ExtensionLoader.java
  src/tools/replay/actors/TracingLock.java
Labels: maintenance

#390 Change the GitLab CI config to run benchmarks and tests in parallel
  .gitlab-ci.yml
  build.xml
  codespeed.conf
  som
Labels: enhancement

#391 Add ValueDictionary to core-lib
  core-lib/Collections.ns
  core-lib/TestSuite/CollectionTests.ns
  src/som/primitives/arrays/ArraySetAllStrategy.java
  tests/dym/expected-results.tar.bz2
  tests/superinstructions/expected-results.tar.bz2
Labels: enhancement

#392 Fix Minitest's #should:signal: and bugs in the testing code
  core-lib/TestSuite/Minitest.ns
  core-lib/TestSuite/MinitestTests.ns
Labels: bug

#317 Fix bug in AsyncTestCase
  build.xml
  core-lib/TestSuite/FileTests.ns
  core-lib/TestSuite/Minitest.ns
  core-lib/TestSuite/MinitestTests.ns
  core-lib/TestSuite/StreamTests.ns
  src/som/compiler/MixinDefinition.java
  src/som/interpreter/nodes/IsValueCheckNode.java
  src/som/primitives/actors/CreateActorPrim.java
  src/som/primitives/processes/ChannelPrimitives.java
Labels: bug
